{{- $releaseName := .Release.Name }}
{{- $releaseVersion := .Release.Revision }}
{{- $chartVersion := .Chart.Version }}
{{- $foo := .Files.Get "files/foo.txt" }}
{{- $bar := (.Files.Glob "files/bar.yml").AsConfig }}
{{- $isEnabled := .Values.somethingEnabled }}
{{- range $cm, $content := .Values.configMaps}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm }}
  namespace: default
  annotations:
    releaseName: {{ $releaseName | quote }}
    releaseVersion: {{ $releaseVersion | quote }}
    chartVersion: {{ $chartVersion | quote }}
data:
{{- range $v := $content }}
  {{ $v.key }} : {{ $v.data }}
{{- end }}
  foo: {{ $foo | quote}}
{{ $bar | indent 2 }}
{{- if $isEnabled }}
  something: "enabled"
{{- else }}
  something: "disabled"
{{- end }}
{{- end }}