{{- $ := . }}
{{- $foo := include "myConfigMaps.foo" . }}
{{- $bar := include "myConfigMaps.bar" . }}
{{- $forceReload := include (print $.Template.BasePath "/_helpers.tpl") . | sha256sum }}
{{- range $cm, $content := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm }}
  namespace: default
  annotations:
    checksum/configmap: {{ $forceReload }}
{{ include "myConfigMaps.releaseAnnotations" $ | nindent 4 }}
{{ include "myConfigMaps.chartAnnotations" $ | nindent 4 }}
{{ include "myConfigMaps.authorAnnotations" $ | nindent 4 }}
data:
{{- range $v := $content }}
  {{ $v.key }} : {{ $v.data }}
{{- end }}
  foo: {{ $foo | quote }}
{{ $bar | nindent 2 }}
{{- include "myConfigMaps.isSomethingEnabled" $ | nindent 2 }}
{{- include "myConfigMaps.doV1andV2Match" $ | nindent 2 }}
{{- include "myConfigMaps.isV3Eq3" $ | nindent 2 }}
{{- include "myConfigMaps.myDefaultValue" $ | nindent 2 }}
{{- include "myConfigMaps.myRequiredValue" $ | nindent 2 }}
{{- end }}