{{- range $cm, $content := .Values.configMaps}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm }}
  namespace: default
data:
{{- range $v := $content }}
  {{ $v.key }} : {{ $v.data }}
{{- end }}
---
{{- end }}