# kubectl create namespace ingress-nginx
# kustomize build . --enable-helm | kubectl apply -f -
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.10.1
    releaseName: ingress-nginx
    namespace: ingress-nginx