{{- if include "api.config.yaml" . }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ include "api.fullname" . }}-config
stringData:
  config.yaml: |
{{ include "api.config.yaml" . | indent 4 }}
{{- end }}
