apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-child
data:
  key: "{{ .Values.global.myKey }}" # my-value or override-value
  password: "{{ .Values.password }}" # parent-password