{{ $releaseName := .Release.Name }}
{{ $releaseNamespace := .Release.Namespace }}
{{ $releaseRevision := .Release.Revision }}
{{ $redisPassword := .Values.redis_password }}
{{- $redisDataPVC := .Values.redis_PersistentVolumeClaim.name }}
{{- with .Values.redis_PersistentVolumeClaim_Bkp }}
{{- if eq .enabled true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .name }}
        image: redis:alpine3.11
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting backup...";
            redis-cli -h redis-{{ $releaseName }}.{{ $releaseNamespace }}.svc.cluster.local \
              -a {{ $redisPassword }} \
              --rdb /backup/dump-{{ $releaseRevision }}.rdb save;
            echo "Backup complete. Contents:";
            ls -lh /backup/
        volumeMounts:
        - name: backup
          mountPath: /backup
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: {{ .name }}
{{- end }}
{{- end }}
