{{- with .Values.redis_PersistentVolumeClaim_Bkp }}
{{- if eq .enabled true }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .name }}
  annotations:
    # pre hooks and weight 0, ensuring it is available before the backup/restore jobs.
    "helm.sh/hook": pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
