version: '3.3'
services:
  app:
    build: .
    image: api:v1.0
    volumes:
      - ./config.yaml:/usr/src/app/config.yaml
    ports:
      - "8080:8000"
  redis:
    image: redis:4.0.11-alpine
    environment:
      - REDIS_PASSWORD=mypassword
      - REDIS_REPLICATION_MODE=master
    command:
      # Save if 100 keys are added in every 10 seconds
      - "--save 10 100"
      # Set password
      - "--requirepass mypassword"
    ports:
      - "6379:6379"